FROM golang:alpine
ENV PORT=8081
ENV GIN_MODE=release
WORKDIR /go/src/wi-util-servers
RUN apk add --no-cache build-base
COPY ./cmd/chat ./cmd/chat/
COPY go.mod .
COPY go.sum .
RUN go install -v ./...
ENTRYPOINT chat
