FROM golang:1.17.5-alpine3.15

ENV PORT=8082
ENV relativeDbPath=./dist/test-db.db
ENV postPublicKey=

WORKDIR /go/src/wi-util-servers
COPY .. .

RUN apk add --no-cache build-base; \
    apk add --no-cache bash; \
    apk add --no-cache sqlite; \
    apk add --no-cache git; \
    go install -v ./...
    
ENV TAG=v4.1.0
RUN cd /; \
    go get -u -d github.com/golang-migrate/migrate/cmd/migrate; \
    cd $GOPATH/src/github.com/golang-migrate/migrate/cmd/migrate; \
    git checkout $TAG; \
    go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@$TAG

RUN cd /go/src/wi-util-servers/scripts; \
    bash migrate.sh

ENTRYPOINT main
