FROM golang:alpine

ENV PORT=8082
ENV relativeDbPath=./dist/db.db
ENV sharedSecret=

WORKDIR /go/src/wi-util-servers

ENV TAG=v4.1.0
RUN apk add --no-cache build-base; \
    apk add --no-cache bash; \
    apk add --no-cache sqlite; \
    apk add --no-cache git; \
    cd /; \
    go get -u -d github.com/golang-migrate/migrate/cmd/migrate; \
    cd $GOPATH/src/github.com/golang-migrate/migrate/cmd/migrate; \
    git checkout $TAG; \
    go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@$TAG

COPY go.mod .
COPY go.sum .
COPY ./cmd/stats ./cmd/stats/
RUN go install -v ./...

COPY ./db ./db/
COPY ./scripts/add-migration.sh ./scripts/
COPY ./scripts/migrate.sh ./scripts/
RUN cd /go/src/wi-util-servers/scripts; \
    bash migrate.sh

ENTRYPOINT main
